// src/lib/supabase.ts
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables')
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
})

// Database types (auto-generated by Supabase, but here's the manual version)
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          username: string | null
          first_name: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          username?: string | null
          first_name?: string | null
        }
        Update: {
          username?: string | null
          first_name?: string | null
        }
      }
      user_favorites: {
        Row: {
          id: string
          user_id: string
          recipe_id: number
          created_at: string
        }
        Insert: {
          user_id: string
          recipe_id: number
        }
        Delete: {
          id: string
        }
      }
      households: {
        Row: {
          id: string
          name: string
          created_by: string
          created_at: string
          updated_at: string
        }
      }
      household_inventory: {
        Row: {
          id: string
          household_id: string
          name: string
          quantity: string | null
          category: string
          added_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          household_id: string
          name: string
          quantity?: string | null
          category?: string
          added_by?: string | null
        }
      }
      household_needed_items: {
        Row: {
          id: string
          household_id: string
          name: string
          added_by: string | null
          created_at: string
        }
        Insert: {
          household_id: string
          name: string
          added_by?: string | null
        }
      }
    }
  }
}